closes Single product component #93
GraceShopper/LisasBikes pull request #111
Opened 2017-04-22 20:35 UTC by chloe630

closes #93 

//a few more things to be done.

2017-04-22 20:50 UTC, gabrielwr requested changes
Looks good overall, Chloe-- good job! See my minor feedback

2017-04-22 20:50 UTC, gabrielwr commented on app/components/SingleProduct.jsx
> +    this.setColor = this.setColor.bide(this)
bind!

2017-04-22 20:50 UTC, gabrielwr commented on app/components/SingleProduct.jsx
> +          <form onSubmit = { this.props.handleSubmit }>
"this.props.handleSubmit" should be "this.props.onSubmitHandle" because of how you wrote it in the connect dispatch.

2017-04-22 20:50 UTC, gabrielwr commented on app/components/SingleProduct.jsx
> +              <a className = "waves-effect waves-light btn-large"
this all looks great!

2017-04-22 20:50 UTC, gabrielwr commented on app/components/SingleProduct.jsx
> +            reviews && reviews.filter(review => review.productId === product.id)
I am pretty sure that what you're trying to achieve here will be managed by the database. For example, each product should have only certain reviews associated with it already, so we won't have to filter through ALL of the reviews. 

Maybe I'm wrong though?

2017-04-22 20:53 UTC, chloe630 commented on app/components/SingleProduct.jsx
> +    this.setColor = this.setColor.bide(this)
omg! will fix the typo right away!

2017-04-22 20:57 UTC, chloe630 commented on app/components/SingleProduct.jsx
> +          <form onSubmit = { this.props.handleSubmit }>
forgot to double check the method names, will fix it as well!

2017-04-23 00:09 UTC, JeffKandel commented on app/components/SingleProduct.jsx
> +            reviews && reviews.filter(review => review.productId === product.id)
@gabrielwr you're right, the database will handle this :-D

2017-04-23 00:11 UTC, chloe630 commented on app/components/SingleProduct.jsx
> +            reviews && reviews.filter(review => review.productId === product.id)
yup! removed the filter!

2017-04-24 20:16 UTC, JeffKandel commented
We know this is failing our CI tests.  We are approving so that the changes can be merged to master for demonstration with the cart.  We will return to fix tests at a later date.

2017-04-24 20:17 UTC, lada-tech approved these changes
keep up good work

2017-04-24 20:18 UTC, merged