closes #29 review api
GraceShopper/LisasBikes pull request #56
Opened 2017-04-19 19:55 UTC by gabrielwr

closes #29

2017-04-19 19:58 UTC, LTochtcheva commented on server/review.js
> +        err.status = 400
the error message should be different )

2017-04-19 19:59 UTC, lada-tech approved these changes
fix error in delete

2017-04-19 20:00 UTC, JeffKandel requested changes
See below, minor cosmetic changes, but one will throw an error!

2017-04-19 20:00 UTC, JeffKandel commented on server/api.js
> +  .use('/reviews', require('./review'))
please change the file name to reviews to stay in line with previous things like users.

2017-04-19 20:00 UTC, JeffKandel commented on server/review.js
> +    .delete('/:id',
Move this back two spaces and delete line 41 or there will be an error

2017-04-20 13:19 UTC, JeffKandel approved these changes
There is room to build out more functionality, but this is a good start.  Let's merge and keep moving forward.

2017-04-20 15:35 UTC, merged